# Generated by Django 4.2.7 on 2025-10-22 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(help_text='Location for weather prediction', max_length=255)),
                ('date', models.DateField(help_text='Date for weather prediction')),
                ('prediction_result', models.CharField(help_text='Prediction result (Rain/No Rain)', max_length=50)),
                ('confidence', models.FloatField(blank=True, help_text='Prediction confidence score', null=True)),
                ('weather_data', models.JSONField(blank=True, help_text='Raw weather data from API', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prediction Request',
                'verbose_name_plural': 'Prediction Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='api_predict_user_id_09b019_idx'), models.Index(fields=['location'], name='api_predict_locatio_cdca79_idx')],
            },
        ),
    ]
